language: go

go:
  - "1.11.x"
env:
  TRAVIS_GO_VERSION: "1.11.x"

script:
  apt-get install curl python-software-properties

  curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

  apt-get install nodejs

  npm install -g truffle

  npm install -g ganache-cli

  npm install -g mocha

  ganache-cli -p 7545 -m "afraid topple foot suffer employ copy version nuclear venue tiger episode check" &

  go test ./...